//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom2_WebBânbanhonl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BANH()
        {
            this.CHITIETDONHANGs = new HashSet<CHITIETDONHANG>();
            this.DANHMUCs = new HashSet<DANHMUC>();
            this.GIOHANGs = new HashSet<GIOHANG>();
        }
    
        public string MaBanh { get; set; }
        public string TenBanh { get; set; }
        public int SoLuong { get; set; }
        public string HinhAnh { get; set; }
        public decimal Gia { get; set; }
        public string MoTa { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHMUC> DANHMUCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIOHANG> GIOHANGs { get; set; }
    }
}
