//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom2_WebBânbanhonl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDONHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHITIETDONHANG()
        {
            this.BANHs = new HashSet<BANH>();
        }
    
        public string MaChiTietDH { get; set; }
        public int SoLuong { get; set; }
        public decimal TongTien { get; set; }
        public string TenBanh { get; set; }
        public decimal DonGia { get; set; }
        public string IdDonHang { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANH> BANHs { get; set; }
    }
}
