//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom2_WebBânbanhonl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VANCHUYEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VANCHUYEN()
        {
            this.DONHANGs = new HashSet<DONHANG>();
        }
    
        public string TrangThai { get; set; }
        public string MaVanChuyen { get; set; }
        public string TenDonVi { get; set; }
        public decimal PhiVanChuyen { get; set; }
        public string ThoiGianGiao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONHANG> DONHANGs { get; set; }
    }
}
